/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "STM32F103x6.h"
#include "GPIO_Interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define PINS_NUM	4

void ClockEnable();
void GPIOInit();


int main(void)
{
	ClockEnable();
	GPIOInit();
	int Value1=0;
	int Value2=0;
	while(1)
	{
		GPIO_u8ReadPinValue(PORTA, PIN1, &Value1);

		while(Value1 ==GPIO_PINLOW)
		{
			GPIO_u8TogglePinValue(PORTB, PIN1);
			/*Polling : Single Pressing*/
			GPIO_u8ReadPinValue(PORTA, PIN1, &Value1);
		}

//		if(Value1==GPIO_PINLOW)
//		{
//			GPIO_u8TogglePinValue(PORTB, PIN1);
//			GPIO_u8ReadPinValue(PORTA, PIN1, &Value1);
//			while(Value1==GPIO_PINLOW);
//
//		}

		while(Value2 ==GPIO_PINHIGH)
		{
			GPIO_u8TogglePinValue(PORTB, PIN13);
			/*Polling : Multi Pressing Pressing*/
			GPIO_u8ReadPinValue(PORTA, PIN13, &Value2);
		}
		for(int i = 0 ; i < 2000 ; i++);

	}

	/* Loop forever */
	for(;;);
}
void ClockEnable()
{
	RCC_GPIOA_CLCK_EN();

	RCC_GPIOB_CLCK_EN();

}
void GPIOInit()
{
	GPIO_PinConfig_S PinsCfg[PINS_NUM] =
	{
			/*PA1 FALOATING iNPUT*/
			{
					.PortNum=PORTA,
					.PinNumber=PIN1,
					.Mode=GPIO_INPUT_Floating,

			},

			{	/*PB1 Output PushPull*/
					.PortNum=PORTB,
					.PinNumber=PIN1,
					.Mode=GPIO_Output_PUSHPULL,
					.Speed=GPIO_LOWSPEED,


			},
			{	/*PA13 HZ --> Floating Input*/
					.PortNum=PORTA,
					.PinNumber=PIN13,
					.Mode=GPIO_INPUT_Floating,

			},
			{	/*PB13 Output PushPull*/
					.PortNum=PORTB,
					.PinNumber=PIN13,
					.Mode=GPIO_Output_PUSHPULL,
					.Speed=GPIO_LOWSPEED,

			},
	};

	for(int counter = 0 ; counter <PINS_NUM ; counter++)
		GPIO_u8PinInit(&PinsCfg[counter]);


}
