/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>


#include "STM32F103x6.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "NVIC_Interface.h"
#include "EXTI_Interface.h"
#include "USART_Interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void CLCK_Init();
void GPIO_Init();


int main(void)
{

	CLCK_Init();
	GPIO_Init();


	USART_HandleTypeDef USART1CFG=
		{
				.BAUDRATE=USART_BaudRate_115200,
				.IRQ_USART_Enable=USART_IRQ_Enable_NONE,
				.PARITY=USART_NO_PARITY,
				.STOP_BITS=USART_ONE_STOP_BITS,
				.USART_DATA_PAYLOAD=USART_8DATA_BITS,
				.USART_MODE=UART_MODE_RX_TX,
				.USART_SELECTION=USART_ONE,
				.USART_STATUE=USART_ENABLE,
				.HwFlowCtl=USART_HwFlowCtl_NONE,

		};

		USART_Init(&USART1CFG);

	uint16_t CH ;


while(1)
{
	USART_U16RecieveData(USART1, &CH, USART_POLLING_ENABLE);

	USART_U16SendData(USART1, &CH, USART_POLLING_ENABLE);


}



	/* Loop forever */
	for(;;);

}

void CLCK_Init()
{

	RCC_GPIOA_CLCK_EN();
	RCC_GPIOB_CLCK_EN();
	AFIO_GPIOA_CLCK_EN();



}
void GPIO_Init()
{
	uint8_t counter ;
	GPIO_PinConfig_S GPIO_PIN[2]=
	{


			//USART1
			{//PA9 TX
					.Mode=GPIO_AF_PP,
					.PinNumber=PIN9,
					.PortNum=PORTA,
					.Speed=GPIO_LOWSPEED
			},
			{//PA10 RX
					.Mode=GPIO_AF_INPUT,
					.PinNumber=PIN10,
					.PortNum=PORTA,

			}

	};

	for(counter = 0 ; counter < 2 ; counter++)
	{
		GPIO_u8PinInit(&GPIO_PIN[counter]);
	}


}
