/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

void RCCInit(void);
void GPIOInit(void);
void EXTIInit(void);

// register address
/*GPIO*/
#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR   *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIO13	    (1UL<<13)
#define GPIOA_CRL	*(volatile uint32_t*)(GPIOA_BASE+0x00)

/*RCC*/
#define RCC_BASE_ADDRESS	0x40021000
#define RCC_CR		*(volatile uint32_t*)(RCC_BASE_ADDRESS)
#define RCC_APB2ENR	*(volatile uint32_t*)(RCC_BASE_ADDRESS+0x18)
#define RCC_CFGR	*(volatile uint32_t*)(RCC_BASE_ADDRESS+0x04)
#define RCC_IOPEN	(1<<2)
/*EXTI*/

#define EXTI_BASE_ADDRESS	0x40010400
#define EXTI_IMR	*(volatile uint32_t*)(EXTI_BASE_ADDRESS)
#define EXTI_EMR	*(volatile uint32_t*)(EXTI_BASE_ADDRESS+0x04)
#define EXTI_RTSR	*(volatile uint32_t*)(EXTI_BASE_ADDRESS+0x08)
#define EXTI_FTSR	*(volatile uint32_t*)(EXTI_BASE_ADDRESS+0x0C)
#define EXTI_SWIER	*(volatile uint32_t*)(EXTI_BASE_ADDRESS+0x10)
#define EXTI_PR		*(volatile uint32_t*)(EXTI_BASE_ADDRESS+0x14)

/*	AFIO		*/
#define AFIO_BASE_ADDRESS	0x40010000
#define AFIO_EXTICR1	    *(volatile uint32_t*)(AFIO_BASE_ADDRESS+0x08)

/*NVIC*/

#define NVIC	0xE000E100
#define NVIC_ISER0	*(volatile uint32_t*)(NVIC)

int main(void)
{

	RCCInit();
	GPIOInit();
	EXTIInit();

	while(1);
}
void RCCInit(void)
{
	/*
		 * Enable RCC FOR GPIOA
		 */
		RCC_APB2ENR|=RCC_IOPEN ;
		/*Enable AFIO CLCK*/
		RCC_APB2ENR|=(1<<0);
		/*PLL Selection*/
		/*SW Pins*/
		RCC_CFGR|=1<<0 ;
		/*APB2 MUX DIV4*/
		RCC_CFGR|=(0b101<<11);
		/*APB1 PRESCALLER /2*/
		RCC_CFGR|=(0b100<<8);


}
void GPIOInit(void)
{
	//Init GPIOA13 OUTPUT PIN
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;

	/*Make PA0 Input with PP PD*/
	GPIOA_CRL|=(0b01<<2);

}
void EXTIInit(void)
{

	/*Enable EXTI0 RISING EDGE */

	EXTI_RTSR|=(1<<0) ;

	/*Enable EXTI0 IMR Interrupt Mask Line 0*/

	EXTI_IMR|=(1<<0) ;

	/*Select AFIO PA0*/

	AFIO_EXTICR1=0;

	/*Enable NVIC*/
	/*Enable IRQ6 */
	NVIC_ISER0|=(1<<6);



}
void EXTI0_IRQHandler(void)
{
	/*Interrupt is happen*/
	/*Toggle Led*/
	GPIOA_ODR ^=GPIO13 ;
//	for (int i = 0; i < 5000; i++); // arbitrary delay

	/*Clear Pending EXTI0 Registers*/
	EXTI_PR|=(1<<0);

}

